-- Fichier genere par node js/outils/catalogue-sql.mjs : ne pas modifier a la main.
-- A coller dans Supabase (SQL Editor) apres schema.sql.
insert into public.objets_catalogue (id, rarete, emplacement, lignes) values
  ('baton-disciple', 'commun', 'arme', '[["atq",3,4]]'::jsonb),
  ('kimono-disciple', 'commun', 'tenue', '[["pv",35,46]]'::jsonb),
  ('bandeau-disciple', 'commun', 'accessoire', '[["vit",1,1]]'::jsonb),
  ('pierre-concentration', 'commun', 'relique', '[["pvPct",1.3,1.7]]'::jsonb),
  ('lame-serment', 'rare', 'arme', '[["atq",6,8],["atqPct",1.2,1.7],["critPct",0.8,1.1]]'::jsonb),
  ('manteau-heros', 'rare', 'tenue', '[["pv",73,98],["atqPct",1.2,1.7]]'::jsonb),
  ('bandeau-promesse', 'rare', 'accessoire', '[["vit",2,2],["energie",3,4]]'::jsonb),
  ('medaille-volonte', 'rare', 'relique', '[["atqPct",2.1,2.8],["critPct",0.8,1.1]]'::jsonb),
  ('bokken-maitre', 'epique', 'arme', '[["atq",10,13],["defPct",2.3,3],["critPct",1.2,1.6]]'::jsonb),
  ('hakama-maitre', 'epique', 'tenue', '[["pv",120,160],["defPct",2.3,3],["pvPct",1.8,2.3]]'::jsonb),
  ('ceinture-noire', 'epique', 'accessoire', '[["vit",2,3],["pvPct",1.8,2.3],["energie",5,6]]'::jsonb),
  ('parchemin-katas', 'epique', 'relique', '[["defPct",3.8,5.1],["atqPct",1.8,2.3],["pvPct",1.8,2.3]]'::jsonb),
  ('gourdin-apprenti', 'commun', 'arme', '[["atq",3,4]]'::jsonb),
  ('gants-sparring', 'peu_commun', 'arme', '[["atq",5,6],["critPct",0.7,0.9]]'::jsonb),
  ('tunique-rapiecee', 'commun', 'tenue', '[["pv",41,54]]'::jsonb),
  ('plastron-bambou', 'peu_commun', 'tenue', '[["pv",72,96],["defPct",1.5,2]]'::jsonb),
  ('sandales-course', 'peu_commun', 'accessoire', '[["vit",1,2],["energie",3,4]]'::jsonb),
  ('trefle-porte-bonheur', 'rare', 'accessoire', '[["vit",2,2],["butin",4,5]]'::jsonb),
  ('cloche-dojo', 'rare', 'relique', '[["defPct",3.1,4.2],["pvPct",1.5,1.9]]'::jsonb),
  ('bandeau-aube', 'legendaire', 'accessoire', '[["vit",3,4],["energie",5,7],["atqPct",1.9,2.6]]'::jsonb),
  ('pique-garnison', 'commun', 'arme', '[["atq",6,8]]'::jsonb),
  ('cotte-garnison', 'commun', 'tenue', '[["pv",77,102]]'::jsonb),
  ('brassard-garnison', 'commun', 'accessoire', '[["vit",2,2]]'::jsonb),
  ('insigne-garnison', 'commun', 'relique', '[["defPct",2.5,3.4]]'::jsonb),
  ('masse-fer', 'rare', 'arme', '[["atq",10,13],["defPct",2.1,2.9]]'::jsonb),
  ('armure-rempart', 'rare', 'tenue', '[["pv",118,158],["defPct",2.1,2.9],["pvPct",1.7,2.2]]'::jsonb),
  ('gantelet-acier', 'rare', 'accessoire', '[["vit",2,3],["defPct",2.1,2.9]]'::jsonb),
  ('sceau-rempart', 'rare', 'relique', '[["defPct",3.6,4.8],["pvPct",1.7,2.2]]'::jsonb),
  ('hallebarde-eternelle', 'epique', 'arme', '[["atq",14,18],["pvPct",2.2,3],["critPct",1.5,2]]'::jsonb),
  ('cuirasse-eternelle', 'epique', 'tenue', '[["pv",172,229],["defPct",2.9,3.8],["pvPct",2.2,3]]'::jsonb),
  ('chaine-gardien', 'epique', 'accessoire', '[["vit",3,4],["defPct",2.9,3.8],["pvPct",2.2,3]]'::jsonb),
  ('cle-forteresse', 'epique', 'relique', '[["pvPct",3.7,5],["defPct",2.9,3.8],["energie",6,8]]'::jsonb),
  ('epee-rouillee', 'commun', 'arme', '[["atq",6,8]]'::jsonb),
  ('arbalete-rempart', 'rare', 'arme', '[["atq",11,14],["critPct",1.2,1.6]]'::jsonb),
  ('gambison', 'commun', 'tenue', '[["pv",83,110]]'::jsonb),
  ('cape-assiege', 'peu_commun', 'tenue', '[["pv",113,150],["pvPct",1.5,2.1]]'::jsonb),
  ('bottes-ferrees', 'peu_commun', 'accessoire', '[["vit",2,3],["defPct",1.8,2.5]]'::jsonb),
  ('lanterne-ronde', 'peu_commun', 'accessoire', '[["vit",2,3],["butin",4,6]]'::jsonb),
  ('blason-fendu', 'rare', 'relique', '[["defPct",4,5.3],["pvPct",1.9,2.5]]'::jsonb),
  ('bouclier-colosse', 'legendaire', 'tenue', '[["pv",190,253],["defPct",3.2,4.2],["pvPct",2.5,3.3]]'::jsonb),
  ('kunai-ombre', 'commun', 'arme', '[["atq",9,12]]'::jsonb),
  ('tenue-ombre', 'commun', 'tenue', '[["pv",113,150]]'::jsonb),
  ('masque-ombre', 'commun', 'accessoire', '[["vit",2,3]]'::jsonb),
  ('fiole-fumee', 'commun', 'relique', '[["critPct",1.7,2.2]]'::jsonb),
  ('kunai-vent', 'rare', 'arme', '[["atq",13,17],["vit",2,2]]'::jsonb),
  ('cape-legere', 'rare', 'tenue', '[["pv",163,218],["vit",2,2]]'::jsonb),
  ('sandales-vent', 'rare', 'accessoire', '[["vit",3,4],["energie",5,7]]'::jsonb),
  ('plume-orage', 'rare', 'relique', '[["atqPct",3.4,4.6],["vit",2,2]]'::jsonb),
  ('katana-nocturne', 'epique', 'arme', '[["atq",18,23],["critPct",1.8,2.4],["atqPct",2.7,3.6]]'::jsonb),
  ('kimono-nocturne', 'epique', 'tenue', '[["pv",224,299],["critPct",1.8,2.4],["vit",2,3]]'::jsonb),
  ('fourreau-lune', 'epique', 'accessoire', '[["vit",4,5],["critPct",1.8,2.4],["atqPct",2.7,3.6]]'::jsonb),
  ('pierre-lunaire', 'epique', 'relique', '[["critPct",3,4],["atqPct",2.7,3.6],["energie",7,9]]'::jsonb),
  ('shuriken-ebreche', 'commun', 'arme', '[["atq",9,11]]'::jsonb),
  ('tanto-silencieux', 'peu_commun', 'arme', '[["atq",11,15],["vit",2,2]]'::jsonb),
  ('manteau-toits', 'commun', 'tenue', '[["pv",119,158]]'::jsonb),
  ('haori-veilleur', 'rare', 'tenue', '[["pv",178,238],["vit",2,3],["critPct",1.5,2]]'::jsonb),
  ('grappin', 'peu_commun', 'accessoire', '[["vit",3,4],["critPct",1.3,1.7]]'::jsonb),
  ('clochette-muette', 'rare', 'accessoire', '[["vit",3,4],["butin",6,8]]'::jsonb),
  ('oeil-de-chat', 'peu_commun', 'relique', '[["critPct",2,2.7],["atqPct",1.8,2.5]]'::jsonb),
  ('murasame-encre', 'legendaire', 'arme', '[["atq",19,26],["critPct",2,2.6],["atqPct",3,4]]'::jsonb),
  ('baton-initie', 'commun', 'arme', '[["atq",12,16]]'::jsonb),
  ('robe-initie', 'commun', 'tenue', '[["pv",149,198]]'::jsonb),
  ('talisman-initie', 'commun', 'accessoire', '[["energie",8,10]]'::jsonb),
  ('encens-initie', 'commun', 'relique', '[["pvPct",3,4]]'::jsonb),
  ('sceptre-scelle', 'rare', 'arme', '[["atq",16,22],["atqPct",2.5,3.3]]'::jsonb),
  ('voile-scelle', 'rare', 'tenue', '[["pv",208,278],["atqPct",2.5,3.3]]'::jsonb),
  ('bague-sceau', 'rare', 'accessoire', '[["vit",4,5],["atqPct",2.5,3.3]]'::jsonb),
  ('sceau-verite', 'rare', 'relique', '[["atqPct",4.1,5.5],["vit",2,3]]'::jsonb),
  ('baton-sage', 'epique', 'arme', '[["atq",22,29],["energie",8,11],["pvPct",3.2,4.2]]'::jsonb),
  ('robe-sage', 'epique', 'tenue', '[["pv",276,368],["pvPct",3.2,4.2],["energie",8,11]]'::jsonb),
  ('chapelet-jade', 'epique', 'accessoire', '[["vit",5,6],["energie",8,11],["pvPct",3.2,4.2]]'::jsonb),
  ('lanterne-esprit', 'epique', 'relique', '[["pvPct",5.3,7],["energie",8,11],["defPct",4,5.4]]'::jsonb),
  ('eventail-papier', 'commun', 'arme', '[["atq",11,15]]'::jsonb),
  ('chakram-runique', 'rare', 'arme', '[["atq",17,23],["energie",7,9],["critPct",1.7,2.3]]'::jsonb),
  ('chale-brume', 'peu_commun', 'tenue', '[["pv",173,231],["vit",2,2]]'::jsonb),
  ('toge-rituel', 'peu_commun', 'tenue', '[["pv",193,258],["pvPct",2.3,3]]'::jsonb),
  ('perles-priere', 'commun', 'accessoire', '[["energie",8,11]]'::jsonb),
  ('miroir-ames', 'rare', 'accessoire', '[["vit",4,5],["butin",7,9]]'::jsonb),
  ('fragment-domaine', 'peu_commun', 'relique', '[["atqPct",3.7,4.9],["energie",6,8]]'::jsonb),
  ('oeil-domaine', 'legendaire', 'relique', '[["critPct",3.9,5.2],["energie",9,12],["vit",3,4]]'::jsonb),
  ('lame-braise', 'commun', 'arme', '[["atq",14,19]]'::jsonb),
  ('cuirasse-braise', 'commun', 'tenue', '[["pv",185,246]]'::jsonb),
  ('anneau-braise', 'commun', 'accessoire', '[["vit",3,4]]'::jsonb),
  ('charbon-ardent', 'commun', 'relique', '[["atqPct",3.6,4.7]]'::jsonb),
  ('epee-legende', 'rare', 'arme', '[["atq",19,26],["atqPct",2.8,3.7],["critPct",1.9,2.5]]'::jsonb),
  ('armure-legende', 'rare', 'tenue', '[["pv",246,328],["pvPct",2.8,3.7],["atqPct",2.8,3.7]]'::jsonb),
  ('couronne-legende', 'rare', 'accessoire', '[["vit",4,6],["atqPct",2.8,3.7],["pvPct",2.8,3.7]]'::jsonb),
  ('etoile-legende', 'rare', 'relique', '[["atqPct",4.7,6.2],["pvPct",2.8,3.7],["critPct",1.9,2.5]]'::jsonb),
  ('plume-lame', 'epique', 'arme', '[["atq",23,30],["atqPct",3.3,4.4],["critPct",2.2,3]]'::jsonb),
  ('manteau-encre', 'epique', 'tenue', '[["pv",294,392],["atqPct",3.3,4.4],["pvPct",3.3,4.4]]'::jsonb),
  ('encrier-sans-fond', 'epique', 'accessoire', '[["vit",5,7],["energie",8,11],["critPct",2.2,3]]'::jsonb),
  ('page-blanche', 'epique', 'relique', '[["critPct",3.7,4.9],["atqPct",3.3,4.4],["energie",8,11]]'::jsonb),
  ('hachette-cendre', 'commun', 'arme', '[["atq",14,19]]'::jsonb),
  ('lance-phenix', 'rare', 'arme', '[["atq",20,26],["critPct",1.9,2.6],["pvPct",2.9,3.8]]'::jsonb),
  ('tunique-ignifugee', 'commun', 'tenue', '[["pv",185,246]]'::jsonb),
  ('ecailles-dragon', 'rare', 'tenue', '[["pv",253,338],["defPct",3.7,4.9],["pvPct",2.9,3.8]]'::jsonb),
  ('bracelet-lave', 'peu_commun', 'accessoire', '[["vit",4,5],["atqPct",2.4,3.3]]'::jsonb),
  ('fer-a-cheval-dore', 'rare', 'accessoire', '[["vit",4,6],["butin",7,10],["critPct",1.9,2.5]]'::jsonb),
  ('coeur-volcan', 'peu_commun', 'relique', '[["atqPct",4.1,5.4],["pvPct",2.4,3.3]]'::jsonb),
  ('plume-rature', 'legendaire', 'relique', '[["atqPct",6.1,8.2],["critPct",2.4,3.3],["energie",9,12]]'::jsonb),
  ('signet-oublie', 'epique', 'arme', '[["atq",26,35],["atqPct",3.7,5],["pvPct",3.7,5]]'::jsonb),
  ('couverture-oubliee', 'epique', 'tenue', '[["pv",337,450],["pvPct",3.7,5],["defPct",4.7,6.3]]'::jsonb),
  ('ruban-oublie', 'epique', 'accessoire', '[["vit",6,8],["atqPct",3.7,5],["energie",9,13]]'::jsonb),
  ('tranche-oubliee', 'epique', 'relique', '[["atqPct",6.2,8.3],["pvPct",3.7,5],["critPct",2.5,3.3]]'::jsonb),
  ('fermoir-acier', 'epique', 'arme', '[["atq",29,39],["defPct",5.2,7],["pvPct",4.1,5.5]]'::jsonb),
  ('reliure-acier', 'epique', 'tenue', '[["pv",381,508],["defPct",5.2,7],["pvPct",4.1,5.5]]'::jsonb),
  ('coins-acier', 'epique', 'accessoire', '[["vit",6,8],["defPct",5.2,7],["pvPct",4.1,5.5]]'::jsonb),
  ('dos-acier', 'epique', 'relique', '[["defPct",8.7,11.6],["pvPct",4.1,5.5],["energie",10,14]]'::jsonb),
  ('coupe-papier', 'epique', 'arme', '[["atq",33,44],["critPct",3,4],["atqPct",4.5,6]]'::jsonb),
  ('jaquette-rouge', 'epique', 'tenue', '[["pv",424,566],["atqPct",4.5,6],["critPct",3,4]]'::jsonb),
  ('marque-page-sanglant', 'epique', 'accessoire', '[["vit",7,9],["critPct",3,4],["atqPct",4.5,6]]'::jsonb),
  ('goutte-encre-rouge', 'epique', 'relique', '[["critPct",5,6.7],["atqPct",4.5,6],["vit",4,6]]'::jsonb),
  ('plume-finale', 'epique', 'arme', '[["atq",36,48],["atqPct",4.9,6.5],["energie",12,17]]'::jsonb),
  ('manteau-epilogue', 'epique', 'tenue', '[["pv",468,624],["pvPct",4.9,6.5],["energie",12,17]]'::jsonb),
  ('sceau-editeur', 'epique', 'accessoire', '[["vit",8,10],["energie",12,17],["critPct",3.3,4.4]]'::jsonb),
  ('derniere-page', 'epique', 'relique', '[["atqPct",8.2,10.9],["critPct",3.3,4.4],["energie",12,17]]'::jsonb),
  ('encre-abysses', 'legendaire', 'relique', '[["atqPct",7.6,10.1],["pvPct",4.5,6],["defPct",5.8,7.7]]'::jsonb),
  ('reliure-resurrection', 'legendaire', 'tenue', '[["pv",468,624],["pvPct",5,6.6],["defPct",6.3,8.4]]'::jsonb),
  ('plume-dernier-mot', 'legendaire', 'arme', '[["atq",40,53],["atqPct",5.4,7.2],["critPct",3.6,4.8]]'::jsonb),
  ('signet-temps', 'legendaire', 'accessoire', '[["vit",8,11],["energie",14,18],["critPct",3.6,4.8]]'::jsonb)
on conflict (id) do update set rarete = excluded.rarete, emplacement = excluded.emplacement, lignes = excluded.lignes;

-- Les persos et leur rarete (pour les echanges de cartes)
insert into public.persos_catalogue (id, rarete) values
  ('goku', 'legendaire'),
  ('vegeta', 'epique'),
  ('piccolo', 'peu_commun'),
  ('naruto', 'rare'),
  ('sasuke', 'epique'),
  ('sakura', 'commun'),
  ('luffy', 'rare'),
  ('zoro', 'rare'),
  ('chopper', 'commun'),
  ('pikachu', 'peu_commun'),
  ('ronflex', 'commun'),
  ('mewtwo', 'legendaire'),
  ('guts', 'epique'),
  ('griffith', 'rare'),
  ('zodd', 'commun'),
  ('gojo', 'legendaire'),
  ('yuji', 'peu_commun'),
  ('megumi', 'commun'),
  ('tanjiro', 'rare'),
  ('nezuko', 'peu_commun'),
  ('zenitsu', 'peu_commun'),
  ('gon', 'commun'),
  ('killua', 'peu_commun'),
  ('kurapika', 'epique'),
  ('c18', 'rare'),
  ('tsunade', 'legendaire'),
  ('nami', 'rare'),
  ('dracaufeu', 'epique'),
  ('chevalier', 'legendaire'),
  ('nobara', 'rare'),
  ('shinobu', 'epique'),
  ('hisoka', 'epique'),
  ('krilin', 'commun'),
  ('freezer', 'epique'),
  ('kakashi', 'epique'),
  ('hinata', 'peu_commun'),
  ('sanji', 'peu_commun'),
  ('robin', 'rare'),
  ('lucario', 'rare'),
  ('florizarre', 'commun'),
  ('casca', 'peu_commun'),
  ('schierke', 'rare'),
  ('sukuna', 'legendaire'),
  ('todo', 'peu_commun'),
  ('rengoku', 'epique'),
  ('inosuke', 'commun'),
  ('netero', 'epique'),
  ('leorio', 'commun'),
  ('ichigo', 'epique'),
  ('rukia', 'rare'),
  ('orihime', 'peu_commun'),
  ('byakuya', 'legendaire'),
  ('kenpachi', 'peu_commun'),
  ('deku', 'rare'),
  ('bakugo', 'epique'),
  ('allmight', 'legendaire'),
  ('uraraka', 'commun'),
  ('todoroki', 'peu_commun'),
  ('eren', 'epique'),
  ('mikasa', 'rare'),
  ('livai', 'legendaire'),
  ('armin', 'commun'),
  ('hange', 'peu_commun'),
  ('denji', 'rare'),
  ('power', 'peu_commun'),
  ('makima', 'legendaire'),
  ('aki', 'rare'),
  ('kobeni', 'commun'),
  ('frieren', 'legendaire'),
  ('fern', 'rare'),
  ('stark', 'peu_commun'),
  ('himmel', 'rare'),
  ('heiter', 'commun'),
  ('natsu', 'epique'),
  ('lucy', 'peu_commun'),
  ('erza', 'epique'),
  ('gray', 'peu_commun'),
  ('wendy', 'commun'),
  ('gohan', 'rare'),
  ('yamcha', 'commun'),
  ('itachi', 'rare'),
  ('rocklee', 'commun'),
  ('shanks', 'legendaire'),
  ('ace', 'epique'),
  ('ectoplasma', 'rare'),
  ('tortank', 'peu_commun'),
  ('serpico', 'peu_commun'),
  ('isidro', 'commun'),
  ('nanami', 'epique'),
  ('maki', 'rare'),
  ('muzan', 'legendaire'),
  ('giyu', 'rare'),
  ('meruem', 'legendaire'),
  ('biscuit', 'rare'),
  ('aizen', 'legendaire'),
  ('uryu', 'rare'),
  ('renji', 'commun'),
  ('shigaraki', 'epique'),
  ('iida', 'peu_commun'),
  ('kirishima', 'commun'),
  ('erwin', 'epique'),
  ('reiner', 'rare'),
  ('jean', 'commun'),
  ('reze', 'epique'),
  ('kishibe', 'rare'),
  ('himeno', 'commun'),
  ('ubel', 'epique'),
  ('aura', 'peu_commun'),
  ('eisen', 'commun'),
  ('zeref', 'legendaire'),
  ('gajeel', 'rare'),
  ('juvia', 'rare'),
  ('saga', 'legendaire'),
  ('shaka', 'epique'),
  ('seiya', 'rare'),
  ('ikki', 'rare'),
  ('shiryu', 'peu_commun'),
  ('aldebaran', 'peu_commun'),
  ('hyoga', 'commun'),
  ('shun', 'commun'),
  ('julius', 'legendaire'),
  ('yami', 'epique'),
  ('asta', 'rare'),
  ('yuno', 'rare'),
  ('noelle', 'peu_commun'),
  ('mereoleona', 'peu_commun'),
  ('luck', 'commun'),
  ('finral', 'commun'),
  ('jinwoo', 'legendaire'),
  ('chahaein', 'epique'),
  ('igris', 'rare'),
  ('beru', 'rare'),
  ('choijongin', 'peu_commun'),
  ('gogunhee', 'peu_commun'),
  ('leejoohee', 'commun'),
  ('yoojinho', 'commun'),
  ('bradley', 'legendaire'),
  ('roy', 'epique'),
  ('edward', 'rare'),
  ('riza', 'rare'),
  ('alphonse', 'peu_commun'),
  ('scar', 'peu_commun'),
  ('armstrong', 'commun'),
  ('winry', 'commun'),
  ('arima', 'legendaire'),
  ('kaneki', 'epique'),
  ('touka', 'rare'),
  ('juuzou', 'rare'),
  ('amon', 'peu_commun'),
  ('rize', 'peu_commun'),
  ('hinami', 'commun'),
  ('nishiki', 'commun'),
  ('dio', 'legendaire'),
  ('jotaro', 'epique'),
  ('joseph', 'rare'),
  ('giorno', 'rare'),
  ('kakyoin', 'peu_commun'),
  ('polnareff', 'peu_commun'),
  ('josuke', 'commun'),
  ('jonathan', 'commun'),
  ('rien', 'legendaire'),
  ('gabimaru', 'epique'),
  ('sagiri', 'rare'),
  ('yuzuriha', 'rare'),
  ('chobe', 'peu_commun'),
  ('shion', 'peu_commun'),
  ('mei', 'commun'),
  ('tenza', 'commun'),
  ('turbogranny', 'legendaire'),
  ('momo', 'epique'),
  ('okarun', 'rare'),
  ('aira', 'rare'),
  ('jiji', 'peu_commun'),
  ('seiko', 'peu_commun'),
  ('vamola', 'commun'),
  ('kashimoto', 'commun'),
  ('narumi', 'legendaire'),
  ('kafka', 'epique'),
  ('mina', 'rare'),
  ('hoshina', 'rare'),
  ('kikoru', 'peu_commun'),
  ('reno', 'peu_commun'),
  ('iharu', 'commun'),
  ('kaiju10', 'commun'),
  ('yor', 'legendaire'),
  ('loid', 'epique'),
  ('anya', 'rare'),
  ('bond', 'rare'),
  ('yuri', 'peu_commun'),
  ('fiona', 'peu_commun'),
  ('franky', 'commun'),
  ('becky', 'commun'),
  ('rin', 'legendaire'),
  ('isagi', 'epique'),
  ('bachira', 'rare'),
  ('nagi', 'rare'),
  ('kunigami', 'peu_commun'),
  ('chigiri', 'peu_commun'),
  ('ego', 'commun'),
  ('kuon', 'commun'),
  ('secret01', 'secret'),
  ('secret02', 'secret'),
  ('secret03', 'secret'),
  ('secret04', 'secret'),
  ('secret05', 'secret'),
  ('secret06', 'secret'),
  ('secret07', 'secret'),
  ('secret08', 'secret'),
  ('secret09', 'secret'),
  ('secret10', 'secret'),
  ('secret11', 'secret'),
  ('secret12', 'secret'),
  ('secret13', 'secret'),
  ('secret14', 'secret'),
  ('secret15', 'secret'),
  ('secret16', 'secret'),
  ('secret17', 'secret'),
  ('secret18', 'secret'),
  ('secret19', 'secret'),
  ('secret20', 'secret'),
  ('secret21', 'secret'),
  ('secret22', 'secret'),
  ('secret23', 'secret'),
  ('secret24', 'secret'),
  ('secret25', 'secret')
on conflict (id) do update set rarete = excluded.rarete;
