// ==========================================================
// SOURCES DES PORTRAITS
// - Tous les persos : AniList, via son API publique (une image tiree de l'anime)
// - Pokemon : en plus, "pokemon" donne l'illustration officielle PokeAPI,
//   affichee en secours tant qu'AniList n'a rien trouve
//     recherche : nom a chercher sur AniList
//     verif     : mot (ou liste de mots) qui doit apparaitre dans le nom trouve,
//                 pour ne jamais afficher le mauvais perso
//     cadrage   : (facultatif) quelle partie de l'image garder,
//                 "50% 0%" = le haut, "50% 50%" = le centre
// ==========================================================

export const SOURCES_PORTRAITS = {
  goku:     { recherche: "Son Goku", verif: "goku" },
  vegeta:   { recherche: "Vegeta", verif: "vegeta" },
  piccolo:  { recherche: "Piccolo", verif: "piccolo" },

  naruto:   { recherche: "Naruto Uzumaki", verif: "uzumaki" },
  sasuke:   { recherche: "Sasuke Uchiha", verif: "sasuke" },
  sakura:   { recherche: "Sakura Haruno", verif: "haruno" },

  luffy:    { recherche: "Monkey D. Luffy", verif: "luffy" },
  zoro:     { recherche: "Roronoa Zoro", verif: "zoro" },
  chopper:  { recherche: "Tony Tony Chopper", verif: "chopper" },

  pikachu:  { recherche: "Pikachu", verif: "pikachu", pokemon: 25 },
  ronflex:  { recherche: "Snorlax", verif: ["snorlax", "kabigon"], pokemon: 143 },
  mewtwo:   { recherche: "Mewtwo", verif: ["mewtwo", "myuutsuu"], pokemon: 150 },

  guts:     { recherche: "Guts", verif: "guts" },
  griffith: { recherche: "Griffith", verif: "griffith" },
  zodd:     { recherche: "Nosferatu Zodd", verif: "zodd" },

  gojo:     { recherche: "Satoru Gojou", verif: "gojo" },
  yuji:     { recherche: "Yuuji Itadori", verif: "itadori" },
  megumi:   { recherche: "Megumi Fushiguro", verif: "fushiguro" },

  tanjiro:  { recherche: "Tanjirou Kamado", verif: "tanjir" },
  nezuko:   { recherche: "Nezuko Kamado", verif: "nezuko" },
  zenitsu:  { recherche: "Zenitsu Agatsuma", verif: "zenitsu" },

  gon:      { recherche: "Gon Freecss", verif: "freecss", cadrage: "50% 30%" },
  killua:   { recherche: "Killua Zoldyck", verif: "killua" },
  kurapika: { recherche: "Kurapika", verif: "kurapika" },

  // Volume 2
  c18:       { recherche: "Android 18", verif: "18" },
  tsunade:   { recherche: "Tsunade", verif: "tsunade" },
  nami:      { recherche: "Nami", verif: "nami" },
  dracaufeu: { recherche: "Charizard", verif: ["charizard", "lizardon"], pokemon: 6 },
  chevalier: { recherche: "Skull Knight", verif: "skull" },
  nobara:    { recherche: "Nobara Kugisaki", verif: "kugisaki" },
  shinobu:   { recherche: "Shinobu Kochou", verif: "kochou" },
  hisoka:    { recherche: "Hisoka", verif: "hisoka" },

  // Volume 3
  krilin:     { recherche: "Krillin", verif: "kri" },
  freezer:    { recherche: "Frieza", verif: "frie" },
  kakashi:    { recherche: "Kakashi Hatake", verif: "kakashi" },
  hinata:     { recherche: "Hinata Hyuuga", verif: "hinata" },
  sanji:      { recherche: "Sanji", verif: "sanji" },
  robin:      { recherche: "Nico Robin", verif: "robin" },
  lucario:    { recherche: "Lucario", verif: "lucario", pokemon: 448 },
  florizarre: { recherche: "Venusaur", verif: ["venusaur", "fushigibana"], pokemon: 3 },
  casca:      { recherche: "Casca", verif: "casca" },
  schierke:   { recherche: "Schierke", verif: "schierke" },
  sukuna:     { recherche: "Sukuna Ryoumen", verif: "sukuna" },
  todo:       { recherche: "Aoi Toudou", verif: "tou" },
  rengoku:    { recherche: "Kyoujurou Rengoku", verif: "rengoku" },
  inosuke:    { recherche: "Inosuke Hashibira", verif: "inosuke" },
  netero:     { recherche: "Isaac Netero", verif: "netero" },
  leorio:     { recherche: "Leorio", verif: "leorio" },
  ichigo:     { recherche: "Ichigo Kurosaki", verif: "ichigo" },
  rukia:      { recherche: "Rukia Kuchiki", verif: "rukia" },
  orihime:    { recherche: "Orihime Inoue", verif: "orihime" },
  byakuya:    { recherche: "Byakuya Kuchiki", verif: "byakuya" },
  kenpachi:   { recherche: "Kenpachi Zaraki", verif: "kenpachi" },
  deku:       { recherche: "Izuku Midoriya", verif: "midoriya" },
  bakugo:     { recherche: "Katsuki Bakugou", verif: "bakugo" },
  allmight:   { recherche: "All Might", verif: "might" },
  uraraka:    { recherche: "Ochaco Uraraka", verif: "uraraka" },
  todoroki:   { recherche: "Shouto Todoroki", verif: "todoroki" },
  eren:       { recherche: "Eren Yeager", verif: "eren" },
  mikasa:     { recherche: "Mikasa Ackerman", verif: "mikasa" },
  livai:      { recherche: "Levi", verif: "levi" },
  armin:      { recherche: "Armin Arlert", verif: "armin" },
  hange:      { recherche: "Hange Zoe", verif: "hange" },
  denji:      { recherche: "Denji", verif: "denji" },
  power:      { recherche: "Power", verif: "power" },
  makima:     { recherche: "Makima", verif: "makima" },
  aki:        { recherche: "Aki Hayakawa", verif: "hayakawa" },
  kobeni:     { recherche: "Kobeni Higashiyama", verif: "kobeni" },
  frieren:    { recherche: "Frieren", verif: "frieren" },
  fern:       { recherche: "Fern", verif: "fern" },
  stark:      { recherche: "Stark", verif: "stark" },
  himmel:     { recherche: "Himmel", verif: "himmel" },
  heiter:     { recherche: "Heiter", verif: "heiter" },
  natsu:      { recherche: "Natsu Dragneel", verif: "natsu" },
  lucy:       { recherche: "Lucy Heartfilia", verif: "heartfilia" },
  erza:       { recherche: "Erza Scarlet", verif: "erza" },
  gray:       { recherche: "Gray Fullbuster", verif: "fullbuster" },
  wendy:      { recherche: "Wendy Marvell", verif: "wendy" },
  // Volume 4
  gohan:      { recherche: "Gohan Son", verif: "gohan" },
  yamcha:     { recherche: "Yamcha", verif: "yamcha" },
  itachi:     { recherche: "Itachi Uchiha", verif: "itachi" },
  rocklee:    { recherche: "Rock Lee", verif: "rock lee" },
  shanks:     { recherche: "Shanks", verif: "shanks" },
  ace:        { recherche: "Portgas D. Ace", verif: "portgas" },
  ectoplasma: { recherche: "Gengar", verif: ["gengar", "gangar"], pokemon: 94 },
  tortank:    { recherche: "Blastoise", verif: ["blastoise", "kamex"], pokemon: 9 },
  serpico:    { recherche: "Serpico", verif: "serpico" },
  isidro:     { recherche: "Isidro", verif: "isidro" },
  nanami:     { recherche: "Kento Nanami", verif: "kento" },
  maki:       { recherche: "Maki Zenin", verif: ["zenin", "zen'in"] },
  muzan:      { recherche: "Muzan Kibutsuji", verif: "muzan" },
  giyu:       { recherche: "Giyuu Tomioka", verif: "tomioka" },
  meruem:     { recherche: "Meruem", verif: "meruem" },
  biscuit:    { recherche: "Biscuit Krueger", verif: "krueger" },
  aizen:      { recherche: "Sousuke Aizen", verif: "aizen" },
  uryu:       { recherche: "Uryuu Ishida", verif: "ishida" },
  renji:      { recherche: "Renji Abarai", verif: "abarai" },
  shigaraki:  { recherche: "Tomura Shigaraki", verif: "shigaraki" },
  iida:       { recherche: "Tenya Iida", verif: "iida" },
  kirishima:  { recherche: "Eijirou Kirishima", verif: "kirishima" },
  erwin:      { recherche: "Erwin Smith", verif: "erwin" },
  reiner:     { recherche: "Reiner Braun", verif: "reiner" },
  jean:       { recherche: "Jean Kirstein", verif: "kirstein" },
  reze:       { recherche: "Reze", verif: "reze" },
  kishibe:    { recherche: "Kishibe", verif: "kishibe" },
  himeno:     { recherche: "Himeno", verif: "himeno" },
  ubel:       { recherche: "Ubel", verif: ["ubel", "übel"] },
  aura:       { recherche: "Aura", verif: "aura" },
  eisen:      { recherche: "Eisen", verif: "eisen" },
  zeref:      { recherche: "Zeref Dragneel", verif: "zeref" },
  gajeel:     { recherche: "Gajeel Redfox", verif: "gajeel" },
  juvia:      { recherche: "Juvia Lockser", verif: "juvia" },
  saga:       { recherche: "Gemini Saga", verif: "saga" },
  shaka:      { recherche: "Virgo Shaka", verif: "shaka" },
  seiya:      { recherche: "Pegasus Seiya", verif: "seiya" },
  ikki:       { recherche: "Phoenix Ikki", verif: "ikki" },
  shiryu:     { recherche: "Dragon Shiryuu", verif: "shiryu" },
  aldebaran:  { recherche: "Taurus Aldebaran", verif: "aldebaran" },
  hyoga:      { recherche: "Cygnus Hyouga", verif: "hyou" },
  shun:       { recherche: "Andromeda Shun", verif: "shun" },
  julius:     { recherche: "Julius Novachrono", verif: "novachrono" },
  yami:       { recherche: "Yami Sukehiro", verif: "sukehiro" },
  asta:       { recherche: "Asta", verif: "asta" },
  yuno:       { recherche: "Yuno Grinberryall", verif: "yuno" },
  noelle:     { recherche: "Noelle Silva", verif: "noelle" },
  mereoleona: { recherche: "Mereoleona Vermillion", verif: "mereoleona" },
  luck:       { recherche: "Luck Voltia", verif: "voltia" },
  finral:     { recherche: "Finral Roulacase", verif: "finral" },
  jinwoo:     { recherche: "Jinwoo Sung", verif: ["jinwoo", "jin-woo", "jin woo"] },
  chahaein:   { recherche: "Haein Cha", verif: ["haein", "hae-in", "hae in"] },
  igris:      { recherche: "Igris", verif: "igris" },
  beru:       { recherche: "Beru", verif: "beru" },
  choijongin: { recherche: "Jongin Choi", verif: ["jongin", "jong-in", "jong in"] },
  gogunhee:   { recherche: "Gunhee Go", verif: ["gunhee", "gun-hee", "gun hee"] },
  leejoohee:  { recherche: "Joohee Lee", verif: ["joohee", "joo-hee", "joo hee"] },
  yoojinho:   { recherche: "Jinho Yoo", verif: ["jinho", "jin-ho", "jin ho"] },
  bradley:    { recherche: "King Bradley", verif: "bradley" },
  roy:        { recherche: "Roy Mustang", verif: "mustang" },
  edward:     { recherche: "Edward Elric", verif: "edward" },
  riza:       { recherche: "Riza Hawkeye", verif: "hawkeye" },
  alphonse:   { recherche: "Alphonse Elric", verif: "alphonse" },
  scar:       { recherche: "Scar", verif: "scar" },
  armstrong:  { recherche: "Alex Louis Armstrong", verif: "armstrong" },
  winry:      { recherche: "Winry Rockbell", verif: "winry" },
  arima:      { recherche: "Kishou Arima", verif: "arima" },
  kaneki:     { recherche: "Ken Kaneki", verif: "kaneki" },
  touka:      { recherche: "Touka Kirishima", verif: "touka" },
  juuzou:     { recherche: "Juuzou Suzuya", verif: "suzuya" },
  amon:       { recherche: "Koutarou Amon", verif: "amon" },
  rize:       { recherche: "Rize Kamishiro", verif: "kamishiro" },
  hinami:     { recherche: "Hinami Fueguchi", verif: "hinami" },
  nishiki:    { recherche: "Nishiki Nishio", verif: "nishio" },
  dio:        { recherche: "Dio Brando", verif: "dio" },
  jotaro:     { recherche: "Joutarou Kuujou", verif: "jou" },
  joseph:     { recherche: "Joseph Joestar", verif: "joseph" },
  giorno:     { recherche: "Giorno Giovanna", verif: "giorno" },
  kakyoin:    { recherche: "Noriaki Kakyouin", verif: "kakyo" },
  polnareff:  { recherche: "Jean Pierre Polnareff", verif: "polnareff" },
  josuke:     { recherche: "Jousuke Higashikata", verif: "higashikata" },
  jonathan:   { recherche: "Jonathan Joestar", verif: "jonathan" },
};
